# Use Node.js 16.14
FROM node:16.14 AS build

# Missing dependencies
RUN apt-get update && apt-get install libsecret-1-dev libx11-dev libxkbfile-dev -y

# Create directories
RUN mkdir -p /home/theia

# Copy your customized Theia project into the image
COPY theia /home/theia

# Set the working directory
WORKDIR /home/theia

ENV NODE_OPTIONS="--max-old-space-size=32768"
#8192

# Build Theia
RUN yarn install
RUN yarn prepare
